### ISSUE TITLE
tweepy error, code 215

### ISSUE THREAD

**Issue by amanabhishk** [IUNetSci/botometer-python#10]
Hi guys! I have been trying to make the example script work. Installed all the dependencies, got the all the keys and stuff. Here is the error I am getting:

```
Traceback (most recent call last):
  File "twitter_bot.py", line 13, in <module>
    result = bom.check_account('@clayadavis')
  File "/Users/aabhishek/anaconda/lib/python2.7/site-packages/botometer/__init__.py", line 113, in check_account
    full_user_object=full_user_object)
  File "/Users/aabhishek/anaconda/lib/python2.7/site-packages/botometer/__init__.py", line 67, in _get_twitter_data
    user_timeline = self.twitter_api.user_timeline(user, count=200)
  File "/Users/aabhishek/anaconda/lib/python2.7/site-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/Users/aabhishek/anaconda/lib/python2.7/site-packages/tweepy/binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{u'message': u'Bad Authentication data.', u'code': 215}]
```

Any help will be appreciated!

**Comment by clayadavis** [comment]
Authentication with Twitter and with Mashape, and since the error you're seeing is a `tweepy TweepError`, it means that there's an issue with your Twitter authentication. Did you fill in your Twitter API keys?

**Comment by amanabhishk** [comment]
Yes, I used the same keys to run a simple tweet-streaming script to be sure that my keys work fine (and they do). I got my mashup keys from the Mashup Market, as shown in the instructions. I am guessing I should not be posting my script with all the keys here?

**Comment by clayadavis** [comment]
Posting your keys is probably not a good idea. The error is clearly with the Twitter authentication (via Tweepy), not Mashape. It might be something as simple as having the key names mixed up?

One thing you can try: after creating your Botometer instance, *e.g.* `bom = botometer.Botometer(...)`, check out the `bom.twitter_api` property. This exposes the [Tweepy API](http://docs.tweepy.org/en/v3.5.0/api.html) object, and you could try something like [`bom.twitter_api.verify_credentials()`](http://docs.tweepy.org/en/v3.5.0/api.html#API.verify_credentials) in order to get information about the authenticated user.

**Comment by amanabhishk** [comment]
It worked, I had a space within the quotes in one of the keys - it feels really stupid. Thanks for all the help!

**Comment by clayadavis** [comment]
Great to hear. Added this to the [Troubleshooting guide](https://github.com/IUNetSci/botometer-python/wiki/Troubleshooting-&-FAQ#tweepyerrortweeperror-bad-authentication-data) in the wiki.
