### ISSUE TITLE
Methods to speed up botometer

### ISSUE THREAD

**Issue by FMCumhaill** [IUNetSci/botometer-python#22]
I'm running botometer on a dataset scrapped from twitter. It's a relativity large dataset. 

I'm wondering if there's any known ways to speed up botometer pinging the twitter sever?

**Comment by clayadavis** [comment]
There are two ratelimits to consider.

First, Twitter limits the number of requests you can make to their API per 15-minute window. If you're analyzing many accounts, you're probably already maxing out these ratelimits, so making faster requests won't help you.

Second, the Botometer API has its own ratelimits. Our free API, the default, limits users to 17,200 requests per day. This is the same as Twitter's search API limit taken over a whole day.

It is possible to use Twitter's app-only authentication in order to get a higher ratelimit from them, as shown in [this wiki page](https://github.com/IUNetSci/botometer-python/wiki/Using-the-Pro-API). In order to make use of this higher ratelimit, you would need to sign up for a paid Pro plan on our [Pro API](https://market.mashape.com/OSoMe/botometer-pro/overview), which has a daily quota matching that of Twitter app-only auth.

Hope that helps, let me know if you have any more questions.
