### ISSUE TITLE
How can I check how much daily quota I have left in Pro API?

### ISSUE THREAD

**Issue by abaheti95** [IUNetSci/botometer-python#38]
Is there any way to know how much of the daily quota I have used while running a code? Can I automatically wait until the next day when the API refreshes the quota limit? How and when is this limit refreshed?

**Comment by clayadavis** [comment]
Since Botometer's ratelimits reflect those of Twitter, you can handle ratelimiting via the underlying Tweepy library. You have two choices:

1. Use a try/except clause to catch Tweepy's `RateLimitError` and handle it appropriately.
2. Pass an optional `wait_on_ratelimit=True` to the API constructor, as shown in the README.

If you use a single Botometer Pro account with a single set of Twitter keys, you shouldn't ever have an issue with overage charges on RapidAPI.

**Comment by abaheti95** [comment]
What if I plan to use muliple twitter keys with the same RapidAPI key. How can I stop for overshooting in that scenario?
