### ISSUE TITLE
HTTPError: 403 Client Error:

### ISSUE THREAD

**Issue by nanciwan** [IUNetSci/botometer-python#51]
. Do you know the reason?
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://botometer-pro.p.rapidapi.com/2/check_account.
Do you know the reason?

**Comment by benabus** [comment]
@nanciwan 403 errors tend to be caused by incorrect or missing API keys.

**Comment by wzy6642** [comment]
I have the same problem, and I have input rapidapi_key.

**Comment by clayadavis** [comment]
RapidAPI may be requiring an extra step. See the solution to this closed issue: https://github.com/IUNetSci/botometer-python/issues/50

**Comment by mr-devs** [comment]
As @clayadavis correctly pointed out in his link to #50, because Rapid API visually allows you to see your rapidAPI key without subscribing to any of the Botometer versions (from the "Endpoints" page), users can copy and paste their rapid API key into their own code attempting to utilize the `botometer-python` package (likely based on the "Quick Start" instructions) prior to subscribing. However, if you have not yet subscribed to any version, you will trigger the `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://botometer-pro.p.rapidapi.com/2/check_account` error. 

The solution is to go to the [Endpoints page](https://rapidapi.com/OSoMe/api/botometer-pro) (after creating a RapidAPI account), clicking `Subscribe to Test`, and then selecting whatever version the user prefers.
